// <auto-generated />
using System;
using ARSPlatform.MODEL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARSPlatform.MODELS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902055244_AddPhasedMaterialsUrlToPhasedReports")]
    partial class AddPhasedMaterialsUrlToPhasedReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("LogId");

                    b.HasIndex(new[] { "AdminId" }, "IX_AuditLog_AdminId");

                    b.HasIndex(new[] { "Timestamp" }, "IX_AuditLog_Timestamp")
                        .IsDescending();

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.CommentVote", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ForumCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId", "ForumCommentId");

                    b.HasIndex("ForumCommentId");

                    b.ToTable("CommentVotes");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.DetailedEvaluation", b =>
                {
                    b.Property<int>("DetailedEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailedEvaluationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("ExpandedCriteria1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpandedCriteria2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpandedCriteria3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinalDecision")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GeneralComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotesFormatting")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotesLiterature")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotesMethodology")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotesOriginality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NotesResults")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReviewRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreFormatting")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreLiterature")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreMethodology")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreOriginality")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreResults")
                        .HasColumnType("int");

                    b.Property<string>("SpecializedEvaluation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailedEvaluationId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex(new[] { "ReviewRequestId" }, "UQ__Detailed__B13067656CE733B3")
                        .IsUnique()
                        .HasFilter("[ReviewRequestId] IS NOT NULL");

                    b.ToTable("DetailedEvaluations");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Follower", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("FollowerId", "FollowedId");

                    b.HasIndex("FollowedId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumComment", b =>
                {
                    b.Property<int>("ForumCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumCommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("ForumPostId")
                        .HasColumnType("int");

                    b.Property<int?>("PaperId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ForumCommentId");

                    b.HasIndex("ForumPostId");

                    b.HasIndex("PaperId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumComments", t =>
                        {
                            t.HasTrigger("trg_ForumComments_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumPost", b =>
                {
                    b.Property<int>("ForumPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForumPostId"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachedPdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("LikeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ForumPostId");

                    b.HasIndex("UserId");

                    b.ToTable("ForumPosts");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumPostLike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ForumPostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId", "ForumPostId");

                    b.HasIndex("ForumPostId");

                    b.ToTable("ForumPostLikes");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<string>("ActivityStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("LeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ResearchGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("ResearchGroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.GuidanceProject", b =>
                {
                    b.Property<int>("GuidanceProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuidanceProjectId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("ResearchGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GuidanceProjectId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ResearchGroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("GuidanceProjects");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.LearningMaterial", b =>
                {
                    b.Property<int>("LearningMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningMaterialId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("SubFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LearningMaterialId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("SubFieldId");

                    b.ToTable("LearningMaterials");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MajorField", b =>
                {
                    b.Property<int>("MajorFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MajorFieldId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MajorFieldId");

                    b.ToTable("MajorFields");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MembershipPackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("SubscriberCount")
                        .HasColumnType("int");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PackageId");

                    b.ToTable("MembershipPackages");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MembershipPurchase", b =>
                {
                    b.Property<int>("PurchasesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchasesId"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePaid")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PurchasesId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("MembershipPurchases");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.OrcidLinkSession", b =>
                {
                    b.Property<int>("OrcidLinkSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrcidLinkSessionId"));

                    b.Property<DateTime?>("AuthenticatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuthenticatedOrcidId")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("TicketHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrcidLinkSessionId");

                    b.HasIndex(new[] { "ExpiresAt" }, "IX_OrcidLinkSessions_ExpiresAt");

                    b.HasIndex(new[] { "UserId" }, "IX_OrcidLinkSessions_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex(new[] { "StateHash" }, "UX_OrcidLinkSessions_StateHash")
                        .IsUnique();

                    b.HasIndex(new[] { "TicketHash" }, "UX_OrcidLinkSessions_TicketHash")
                        .IsUnique()
                        .HasFilter("[TicketHash] IS NOT NULL");

                    b.ToTable("OrcidLinkSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrcidLinkSessions_AccountLinkUser", "[Context] <> 'ACCOUNT_LINK' OR [UserId] IS NOT NULL");

                            t.HasCheckConstraint("CK_OrcidLinkSessions_Context", "[Context] IN ('REGISTRATION', 'ACCOUNT_LINK')");

                            t.HasCheckConstraint("CK_OrcidLinkSessions_RegistrationUser", "[Context] <> 'REGISTRATION' OR [UserId] IS NULL");

                            t.HasCheckConstraint("CK_OrcidLinkSessions_Status", "[Status] IN ('PENDING', 'AUTHENTICATED', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Paper", b =>
                {
                    b.Property<int>("PaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaperId"));

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorshipVerificationReason")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AuthorshipVerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("NOT_CHECKED");

                    b.Property<DateTime?>("AuthorshipVerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsOpenAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("Issn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IssnValue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OpenAlexWorkId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Quartile")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("SourceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SubFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("PaperId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SubFieldId");

                    b.ToTable("Papers", t =>
                        {
                            t.HasTrigger("trg_Papers_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.PaperAuthor", b =>
                {
                    b.Property<int>("PaperAuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaperAuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AuthorOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool?>("IsCorresponding")
                        .HasColumnType("bit");

                    b.Property<string>("OpenAlexAuthorId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OrcidId")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)");

                    b.Property<int>("PaperId")
                        .HasColumnType("int");

                    b.Property<string>("RawAuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PaperAuthorId");

                    b.HasIndex(new[] { "OrcidId" }, "IX_PaperAuthors_OrcidId")
                        .HasFilter("[OrcidId] IS NOT NULL");

                    b.HasIndex(new[] { "PaperId" }, "IX_PaperAuthors_PaperId");

                    b.ToTable("PaperAuthors", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperAuthors_AuthorOrder", "[AuthorOrder]>(0)");

                            t.HasCheckConstraint("CK_PaperAuthors_Source", "[Source]='MANUAL' OR [Source]='OPENALEX'");
                        });
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.PhasedReport", b =>
                {
                    b.Property<int>("PhasedReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhasedReportId"));

                    b.Property<string>("CapacityEvaluation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("DeadlineAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinalOutcomeEvaluation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("GroupMemberId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LectureFeedback")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("LecturerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MilestoneTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PhaseNumber")
                        .HasColumnType("int");

                    b.Property<string>("PhasedMaterialsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReportFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResearchGroupId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("PhasedReportId");

                    b.HasIndex("GroupMemberId");

                    b.HasIndex("ResearchGroupId");

                    b.HasIndex("TopicId");

                    b.ToTable("PhasedReports", t =>
                        {
                            t.HasTrigger("trg_PhasedReports_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ProfessionalProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Hindex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("HIndex");

                    b.Property<string>("OrcidId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PublicationCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ReviewFee")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int?>("SubFieldId")
                        .HasColumnType("int");

                    b.Property<string>("SyncStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TotalCitations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("UserId");

                    b.HasIndex("SubFieldId");

                    b.ToTable("ProfessionalProfiles", t =>
                        {
                            t.HasTrigger("trg_ProfessionalProfiles_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Profile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarInitials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Institution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Profile", (string)null);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("ViolationNotes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReportId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports", t =>
                        {
                            t.HasTrigger("trg_Reports_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchGroup", b =>
                {
                    b.Property<int>("ResearchGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearchGroupId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("MaterialsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("ResearchGroupId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("TopicId");

                    b.ToTable("ResearchGroups");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuidanceProjectsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("TopicId");

                    b.HasIndex("LecturerId");

                    b.ToTable("ResearchTopics", t =>
                        {
                            t.HasTrigger("trg_ResearchTopics_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ReviewRequest", b =>
                {
                    b.Property<int>("ReviewRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewRequestId"));

                    b.Property<bool?>("Airecommended")
                        .HasColumnType("bit")
                        .HasColumnName("AIRecommended");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int?>("PaperId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ReviewRequestId");

                    b.HasIndex("PaperId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ReviewRequest", (string)null);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2026, 9, 2, 5, 52, 43, 232, DateTimeKind.Utc).AddTicks(5498),
                            Name = "Lecturer"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2026, 9, 2, 5, 52, 43, 232, DateTimeKind.Utc).AddTicks(5507),
                            Name = "Graduate Student"
                        });
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.RoleRequest", b =>
                {
                    b.Property<int>("RoleRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleRequestId"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProofDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequestedRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleRequestId");

                    b.HasIndex("RequestedRoleId");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("UserId");

                    b.ToTable("RoleRequests");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Seminar", b =>
                {
                    b.Property<int>("SeminarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeminarId"));

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OnlineLink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<bool>("ReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SeminarId");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Seminars");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SeminarParticipant", b =>
                {
                    b.Property<int>("SeminarParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeminarParticipantId"));

                    b.Property<DateTime?>("EventReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FeedbackReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("InvitationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvitationStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InvitedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParticipantEvaluation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("SeminarId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SeminarParticipantId");

                    b.HasIndex("SeminarId");

                    b.HasIndex("UserId");

                    b.ToTable("SeminarParticipants");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SharedMaterial", b =>
                {
                    b.Property<int>("SharedMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SharedMaterialId"));

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("PaperId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SharedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("SharedWithColleagueId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SharedMaterialId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("PaperId");

                    b.HasIndex("SharedWithColleagueId");

                    b.ToTable("SharedMaterials");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SubField", b =>
                {
                    b.Property<int>("SubFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubFieldId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradingRubric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MajorFieldId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubFieldId");

                    b.HasIndex("MajorFieldId");

                    b.ToTable("SubFields");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("AccountTier")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ExpiresOtpAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsAvailableForReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsOrcidVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsOtpUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxSimultaneousPapers")
                        .HasColumnType("int");

                    b.Property<string>("OrcidDisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OrcidId")
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)");

                    b.Property<DateTime?>("OrcidVerifiedAt")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProofDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("VerificationStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105342E34C60E")
                        .IsUnique();

                    b.HasIndex(new[] { "GoogleId" }, "UX_User_GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex(new[] { "OrcidId" }, "UX_User_OrcidId")
                        .IsUnique()
                        .HasFilter("[OrcidId] IS NOT NULL");

                    b.ToTable("User", null, t =>
                        {
                            t.HasTrigger("trg_User_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UserRole");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId", "RoleId" }, "UX_UserRole_UserId_RoleId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [RoleId] IS NOT NULL");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.UserToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "RefreshToken" }, "UQ__UserToke__DEA298DA118F54B9")
                        .IsUnique();

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex(new[] { "UserId" }, "UQ__Wallets__1788CC4D1AA07263")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Wallets", t =>
                        {
                            t.HasTrigger("trg_Wallets_update");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.WithdrawalRequest", b =>
                {
                    b.Property<int>("WithdrawalRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WithdrawalRequestId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WithdrawalRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("WithdrawalRequests", (string)null);
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.AuditLog", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.CommentVote", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.ForumComment", "ForumComment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("ForumCommentId")
                        .IsRequired()
                        .HasConstraintName("FK__CommentVo__Forum__02FC7413");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("CommentVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CommentVo__UserI__02084FDA");

                    b.Navigation("ForumComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.DetailedEvaluation", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.ReviewRequest", "ReviewRequest")
                        .WithOne("DetailedEvaluation")
                        .HasForeignKey("ARSPlatform.MODEL.Entities.DetailedEvaluation", "ReviewRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__DetailedE__Revie__75A278F5");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Reviewer")
                        .WithMany("DetailedEvaluations")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__DetailedE__Revie__76969D2E");

                    b.Navigation("ReviewRequest");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Follower", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Followed")
                        .WithMany("FollowerFolloweds")
                        .HasForeignKey("FollowedId")
                        .IsRequired()
                        .HasConstraintName("FK__Followers__Follo__5812160E");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "FollowerNavigation")
                        .WithMany("FollowerFollowerNavigations")
                        .HasForeignKey("FollowerId")
                        .IsRequired()
                        .HasConstraintName("FK__Followers__Follo__571DF1D5");

                    b.Navigation("Followed");

                    b.Navigation("FollowerNavigation");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumComment", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.ForumPost", "ForumPost")
                        .WithMany("ForumComments")
                        .HasForeignKey("ForumPostId");

                    b.HasOne("ARSPlatform.MODEL.Entities.Paper", "Paper")
                        .WithMany("ForumComments")
                        .HasForeignKey("PaperId")
                        .HasConstraintName("FK__ForumComm__Paper__7B5B524B");

                    b.HasOne("ARSPlatform.MODEL.Entities.ForumComment", "Reply")
                        .WithMany("InverseReply")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FK__ForumComm__Reply__7C4F7684");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("ForumComments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ForumComm__UserI__7A672E12");

                    b.Navigation("ForumPost");

                    b.Navigation("Paper");

                    b.Navigation("Reply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumPost", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("ForumPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ForumPosts__UserId__7D439ABD");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumPostLike", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.ForumPost", "ForumPost")
                        .WithMany("ForumPostLikes")
                        .HasForeignKey("ForumPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ForumPostLikes_ForumPost");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("ForumPostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ForumPostLikes_User");

                    b.Navigation("ForumPost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.GroupMember", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.ResearchGroup", "ResearchGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("ResearchGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__GroupMemb__Resea__14270015");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Student")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__GroupMemb__Stude__151B244E");

                    b.Navigation("ResearchGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.GuidanceProject", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Lecturer")
                        .WithMany("GuidanceProjectLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__GuidanceP__Lectu__1DB06A4F");

                    b.HasOne("ARSPlatform.MODEL.Entities.ResearchGroup", "ResearchGroup")
                        .WithMany("GuidanceProjects")
                        .HasForeignKey("ResearchGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Student")
                        .WithMany("GuidanceProjectStudents")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__GuidanceP__Stude__1F98B2C1");

                    b.Navigation("Lecturer");

                    b.Navigation("ResearchGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.LearningMaterial", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Lecturer")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__LearningM__Lectu__18EBB532");

                    b.HasOne("ARSPlatform.MODEL.Entities.SubField", "SubField")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__LearningM__SubFi__1AD3FDA4");

                    b.Navigation("Lecturer");

                    b.Navigation("SubField");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MembershipPurchase", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.MembershipPackage", "Package")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK__Membershi__Packa__6A30C649");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("MembershipPurchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Membershi__UserI__693CA210");

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Notification", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Notificat__UserI__3E1D39E1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.OrcidLinkSession", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_OrcidLinkSessions_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Paper", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Creator")
                        .WithMany("Papers")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Papers__CreatorI__4F7CD00D");

                    b.HasOne("ARSPlatform.MODEL.Entities.SubField", "SubField")
                        .WithMany("Papers")
                        .HasForeignKey("SubFieldId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Papers__SubField__5441852A");

                    b.Navigation("Creator");

                    b.Navigation("SubField");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.PaperAuthor", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Paper", "Paper")
                        .WithMany("PaperAuthors")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaperAuthors_Papers");

                    b.Navigation("Paper");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.PhasedReport", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.GroupMember", "GroupMember")
                        .WithMany("PhasedReports")
                        .HasForeignKey("GroupMemberId")
                        .HasConstraintName("FK__PhasedRep__Group__236943A5");

                    b.HasOne("ARSPlatform.MODEL.Entities.ResearchGroup", "ResearchGroup")
                        .WithMany("PhasedReports")
                        .HasForeignKey("ResearchGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PhasedRep__Resea__22751F6C");

                    b.HasOne("ARSPlatform.MODEL.Entities.ResearchTopic", "Topic")
                        .WithMany("PhasedReports")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GroupMember");

                    b.Navigation("ResearchGroup");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ProfessionalProfile", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.SubField", "SubField")
                        .WithMany("ProfessionalProfiles")
                        .HasForeignKey("SubFieldId");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithOne("ProfessionalProfile")
                        .HasForeignKey("ARSPlatform.MODEL.Entities.ProfessionalProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Professio__UserI__4222D4EF");

                    b.Navigation("SubField");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Profile", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ARSPlatform.MODEL.Entities.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Profile__UserId__31B762FC");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Report", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Reporter")
                        .WithMany("Reports")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FK__Reports__Reporte__06CD04F7");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchGroup", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Lecturer")
                        .WithMany("ResearchGroups")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ResearchG__Lectu__0F624AF8");

                    b.HasOne("ARSPlatform.MODEL.Entities.ResearchTopic", "Topic")
                        .WithMany("ResearchGroups")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__ResearchG__Topic__10566F31");

                    b.Navigation("Lecturer");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchTopic", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Lecturer")
                        .WithMany("ResearchTopics")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ReviewRequest", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Paper", "Paper")
                        .WithMany("ReviewRequests")
                        .HasForeignKey("PaperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__ReviewReq__Paper__6EF57B66");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Reviewer")
                        .WithMany("ReviewRequests")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("FK__ReviewReq__Revie__6FE99F9F");

                    b.Navigation("Paper");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.RoleRequest", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Role", "RequestedRole")
                        .WithMany("RoleRequests")
                        .HasForeignKey("RequestedRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RoleRequests__RequestedRoleId");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("RoleRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__RoleRequests__UserId");

                    b.Navigation("RequestedRole");

                    b.Navigation("ReviewedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Seminar", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Organizer")
                        .WithMany("Seminars")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Seminars__Organi__2CF2ADDF");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SeminarParticipant", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Seminar", "Seminar")
                        .WithMany("SeminarParticipants")
                        .HasForeignKey("SeminarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SeminarPa__Semin__42E1EEFE");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("SeminarParticipants")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__SeminarPa__UserI__43D61337");

                    b.Navigation("Seminar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SharedMaterial", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "Lecturer")
                        .WithMany("SharedMaterialLecturers")
                        .HasForeignKey("LecturerId")
                        .HasConstraintName("FK__SharedMat__Lectu__2739D489");

                    b.HasOne("ARSPlatform.MODEL.Entities.Paper", "Paper")
                        .WithMany("SharedMaterials")
                        .HasForeignKey("PaperId")
                        .HasConstraintName("FK__SharedMat__Paper__282DF8C2");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "SharedWithColleague")
                        .WithMany("SharedMaterialSharedWithColleagues")
                        .HasForeignKey("SharedWithColleagueId")
                        .HasConstraintName("FK__SharedMat__Share__29221CFB");

                    b.Navigation("Lecturer");

                    b.Navigation("Paper");

                    b.Navigation("SharedWithColleague");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SubField", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.MajorField", "MajorField")
                        .WithMany("SubFields")
                        .HasForeignKey("MajorFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__SubFields__Major__4BAC3F29");

                    b.Navigation("MajorField");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Transaction", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Transacti__Walle__619B8048");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.UserRole", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserRole__RoleId__3A4CA8FD");

                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserRole__UserId__395884C4");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.UserToken", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__UserToken__UserI__3587F3E0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Wallet", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("ARSPlatform.MODEL.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Wallets__UserId__5CD6CB2B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.WithdrawalRequest", b =>
                {
                    b.HasOne("ARSPlatform.MODEL.Entities.User", "User")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WithdrawalRequests_User");

                    b.HasOne("ARSPlatform.MODEL.Entities.Wallet", "Wallet")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FK_WithdrawalRequests_Wallet");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumComment", b =>
                {
                    b.Navigation("CommentVotes");

                    b.Navigation("InverseReply");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ForumPost", b =>
                {
                    b.Navigation("ForumComments");

                    b.Navigation("ForumPostLikes");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.GroupMember", b =>
                {
                    b.Navigation("PhasedReports");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MajorField", b =>
                {
                    b.Navigation("SubFields");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.MembershipPackage", b =>
                {
                    b.Navigation("MembershipPurchases");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Paper", b =>
                {
                    b.Navigation("ForumComments");

                    b.Navigation("PaperAuthors");

                    b.Navigation("ReviewRequests");

                    b.Navigation("SharedMaterials");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchGroup", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("GuidanceProjects");

                    b.Navigation("PhasedReports");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ResearchTopic", b =>
                {
                    b.Navigation("PhasedReports");

                    b.Navigation("ResearchGroups");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.ReviewRequest", b =>
                {
                    b.Navigation("DetailedEvaluation");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Role", b =>
                {
                    b.Navigation("RoleRequests");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Seminar", b =>
                {
                    b.Navigation("SeminarParticipants");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.SubField", b =>
                {
                    b.Navigation("LearningMaterials");

                    b.Navigation("Papers");

                    b.Navigation("ProfessionalProfiles");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.User", b =>
                {
                    b.Navigation("CommentVotes");

                    b.Navigation("DetailedEvaluations");

                    b.Navigation("FollowerFolloweds");

                    b.Navigation("FollowerFollowerNavigations");

                    b.Navigation("ForumComments");

                    b.Navigation("ForumPostLikes");

                    b.Navigation("ForumPosts");

                    b.Navigation("GroupMembers");

                    b.Navigation("GuidanceProjectLecturers");

                    b.Navigation("GuidanceProjectStudents");

                    b.Navigation("LearningMaterials");

                    b.Navigation("MembershipPurchases");

                    b.Navigation("Notifications");

                    b.Navigation("Papers");

                    b.Navigation("ProfessionalProfile");

                    b.Navigation("Profile");

                    b.Navigation("Reports");

                    b.Navigation("ResearchGroups");

                    b.Navigation("ResearchTopics");

                    b.Navigation("ReviewRequests");

                    b.Navigation("RoleRequests");

                    b.Navigation("SeminarParticipants");

                    b.Navigation("Seminars");

                    b.Navigation("SharedMaterialLecturers");

                    b.Navigation("SharedMaterialSharedWithColleagues");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");

                    b.Navigation("Wallet");

                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("ARSPlatform.MODEL.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("WithdrawalRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
